services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - motivation-letter-bot_postgres_data:/var/lib/postgresql/data
      - ./imports/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql

volumes:
  motivation-letter-bot_postgres_data:
