spring:
  aop:
    proxy-target-class: true
  main:
    banner-mode: "off"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: motivation-letter-bot
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: MotivationLetterBot
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.default_schema: ${POSTGRES_SCHEMA:motivation_letter_bot_schema}
  liquibase:
    default-schema: ${POSTGRES_SCHEMA:motivation_letter_bot_schema}
    change-log: classpath:db/changelog/master.yml

logging:
  level:
    root: WARN

bot:
   name: "MotivationLetterBot"
   token: ${BOT_TOKEN:8068325542:AAEanbwFmZ_uLykXOgTf1D9CrLlyNQ52FfI}


motivation-bot:
  kafka:
    request-topic: motivation-bot-requests
    response-topic: motivation-bot-responses
