spring:
  application:
    name: MotivationLetterBot
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: ${POSTGRES_SCHEMA:motivation_letter_bot_schema}
  liquibase:
    default-schema: ${POSTGRES_SCHEMA:motivation_letter_bot_schema}
    change-log: classpath:db/changelog/master.yml

bot:
  name: "MotivationLetterBot"
  token: ${BOT_TOKEN:}
