spring:
  main:
    banner-mode: "off"

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: motivation-letter-bot
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: MotivationLetterBot

logging:
  level:
    org.telegram.telegrambots: ERROR
    org.telegram.telegrambots.longpolling.BotSession: OFF
    root: WARN
  pattern:
    console: "%msg%n"

bot:
  name: "MotivationLetterBot"
  token: ${BOT_TOKEN:8068325542:AAEanbwFmZ_uLykXOgTf1D9CrLlyNQ52FfI}
  bot-creator-id: ${BOT_CREATOR_ID:946550660}

motivation-bot:
  kafka:
    request-topic: motivation-bot-requests
    response-topic: motivation-bot-responses
